### ISSUE TITLE
Nextjs ReferenceError: window is not defined

### ISSUE THREAD

**Issue by usuarez** [AgoraIO/RTM#152] opened 2021-08-18 21:35 UTC
Hello, when i try to import the sdk in nextjs
`import AgoraRTM from 'agora-rtm-sdk'`

this message appears and i can't fix
![screenshot (1)](https://user-images.githubusercontent.com/37843358/129975183-ebcb97bb-8b9b-46df-9774-82c8c662e68f.png)

**Comment by akazwz** [comment] 2021-11-10 12:39
Hello, I have the same question, this may be caused by the SSR, u can import this dynamic by using 'next/dynamic' without SSR, it works for me, I will show u the code.
You should write ur main code in another component, then import it like this
````ts
import dynamic from 'next/dynamic'

const Message = dynamic(
    () => import('../src/components/Message'),
    {ssr: false})

const IndexPage = () => {
    return (
        <>
            <Message/>
        </>
    )
}

export default IndexPage
````

**Comment by Hexa-IT** [comment] 2022-07-08 16:39
> Hello, I have the same question, this may be caused by the SSR, u can import this dynamic by using 'next/dynamic' without SSR, it works for me, I will show u the code. You should write ur main code in another component, then import it like this
> 
> ```ts
> import dynamic from 'next/dynamic'
> 
> const Message = dynamic(
>     () => import('../src/components/Message'),
>     {ssr: false})
> 
> const IndexPage = () => {
>     return (
>         <>
>             <Message/>
>         </>
>     )
> }
> 
> export default IndexPage
> ```

That does indeed fix it when running the application. But when creating a production build `next build` the error pops up again. Anyone have a fix for this?

**Comment by usuarez** [comment] 2022-07-08 17:58
@Hexa-IT @akazwz i fix this using an async import in an useEffect hook cuz the next dynamic has problems with components memorization and it re render the component in each interaction

**Comment by Hexa-IT** [comment] 2022-07-08 22:08
> @Hexa-IT @akazwz i fix this using an async import in an useEffect hook cuz the next dynamic has problems with components memorization and it re render the component in each interaction

Thanks I've implemented this. Works like a charm!

`const AgoraRTC = (await import('agora-rtc-sdk-ng')).default;`

**Closed** 2022-07-11 01:50 UTC

**Comment by jeoffreyduke** [comment] 2022-07-29 00:31
> > @Hexa-IT @akazwz i fix this using an async import in an useEffect hook cuz the next dynamic has problems with components memorization and it re render the component in each interaction
> 
> Thanks I've implemented this. Works like a charm!
> 
> ```
> const AgoraRTC = (await import('agora-rtc-sdk-ng')).default;
> ```

bro, how did you implement this?

**Comment by daivy** [comment] 2022-08-24 10:00
I hate it but it works, you're gonna have to null check it everywhere though.

```js
  const initAgora = async (): Promise<IAgoraRTC> => {
    return (await import("agora-rtc-sdk-ng")).default;
  };

  const [AgoraRTC, setAgoraRTC] = useState<IAgoraRTC | null>(null);

  initAgora().then(agora => {
    setAgoraRTC(agora);
  });

  // example implementation
  const agoraClient = useMemo(() => {
    if (!AgoraRTC) {
      return;
    }

    const client = AgoraRTC.createClient(...);

    client.on("user-joined", (user: IAgoraRTCRemoteUser) => {
      // yada yada yada
    });

    return client;
  }, [AgoraRTC]);

```

Will update if I find a better solution, let's hope so because this is... yikes.

**Comment by ShakibUddin** [comment] 2023-06-12 04:39
> Hello, I have the same question, this may be caused by the SSR, u can import this dynamic by using 'next/dynamic' without SSR, it works for me, I will show u the code. You should write ur main code in another component, then import it like this
> 
> ```ts
> import dynamic from 'next/dynamic'
> 
> const Message = dynamic(
>     () => import('../src/components/Message'),
>     {ssr: false})
> 
> const IndexPage = () => {
>     return (
>         <>
>             <Message/>
>         </>
>     )
> }
> 
> export default IndexPage
> ```

This works for me. Thanks

**Comment by azad-nft** [comment] 2024-03-01 15:03
> Hello, I have the same question, this may be caused by the SSR, u can import this dynamic by using 'next/dynamic' without SSR, it works for me, I will show u the code. You should write ur main code in another component, then import it like this
> 
> ```ts
> import dynamic from 'next/dynamic'
> 
> const Message = dynamic(
>     () => import('../src/components/Message'),
>     {ssr: false})
> 
> const IndexPage = () => {
>     return (
>         <>
>             <Message/>
>         </>
>     )
> }
> 
> export default IndexPage
> ```

That worked for me perfectly,
